#!/usr/bin/env bash
#MISE description="Build docs for production"
#MISE sources=["**/*.{ts,tsx,mdoc,css}", "!node_modules/**", "!.next/**"]
#MISE outputs={auto=true}
mise run //docs:lint
bun run build
